[package]
name = "mnist_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blowtorch = "0.1.0"
ndarray-npy = "0.8.0"
